### ISSUE TITLE
"MAC check failed" for some OSes

### ISSUE THREAD

**Issue by EmilienCourt** [fox-it/dissect.hypervisor#40]
Hi,

I've been using `dissect.hypervisor` as a library in a project to decrypt files from an ESXi.

Everything is working fine on Ubuntu, but on my macOS I can't use the `decrypt` function from the `Envelope` class : `pycryptodome` will throw an `ValueError("MAC check failed")` when doing MAC verification : https://github.com/Legrandin/pycryptodome/blob/master/lib/Crypto/Cipher/_mode_gcm.py#L508.

The output bytes are however perfectly fine, and I don't mind the MAC verification for this project.

Would it be possible to add an optional argument when instantiating the Envelope class so that Envelope's [cipher.verify](https://github.com/fox-it/dissect.hypervisor/blob/f01a1d2f8a7e9a74186aca8017bf99fa2e4d9c7b/dissect/hypervisor/util/envelope.py#L193) is not called ?

Thanks a lot :)

Regards,

**Comment by Schamper** [comment]
Interesting that there's a discrepancy between Linux and macOS... Might be interesting to investigate that at some point, but adding a flag whether to verify or not is a good addition nonetheless!

**Comment by EmilienCourt** [comment]
Agreed !

Testing might be difficult as this issue only occurs on some archives, and we are not the ones generating those :)

I've added the flag in a PR : https://github.com/fox-it/dissect.hypervisor/pull/41

Regards,
